### ISSUE TITLE
npm install "broken"

### ISSUE THREAD

**Issue by kazzkiq** [grvcoelho/spokesman#20]
When using the command:
```
npm install @grvcoelho/babelfish --save
```

I'm given the following error:

```bash
npm ERR! 404  '@grvcoelho/babelfish' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Has this project been pushed to npm registry? Perhaps a simple `npm publish` can solve this?

Awesome project, btw.

**Comment by kazzkiq** [comment]
@grvcoelho Any idea of this? Is the project still maintained?

**Comment by grvcoelho** [comment]
Hey, just fixed @kazzkiq  :)

Sorry for the delay :+1:
